
export const adminActionsName={
    START_GET_USERS:'  START_GET_USERS',
    SUCCESS_GET_USERS:'SUCCESS_GET_USERS',
    FAIL_GET_USERS:'  FAIL_GET_USERS',

    START_GET_ORDERS:'  START_GET_ORDERS',
    SUCCESS_GET_ORDERS:'SUCCESS_GET_ORDERS',
    FAIL_GET_ORDERS:'  FAIL_GET_ORDERS',

    START_UPDATE_DETAILES_SPESIFIC_ORDER:'  START_UPDATE_DETAILES_SPESIFIC_ORDER',
    SUCCESS_UPDATE_DETAILES_SPESIFIC_ORDER:'SUCCESS_UPDATE_DETAILES_SPESIFIC_ORDER',
    FAIL_UPDATE_DETAILES_SPESIFIC_ORDER:'  FAIL_UPDATE_DETAILES_SPESIFIC_ORDER',

    
    START_UPDATE_DETAILES_SPESIFIC_PRODUCT:'  START_UPDATE_DETAILES_SPESIFIC_PRODUCT',
    SUCCESS_UPDATE_DETAILES_SPESIFIC_PRODUCT:'SUCCESS_UPDATE_DETAILES_SPESIFIC_PRODUCT',
    FAIL_UPDATE_DETAILES_SPESIFIC_PRODUCT:'  FAIL_UPDATE_DETAILES_SPESIFIC_PRODUCT',

    START_UPDATE_DETAILES_SPESIFIC_USER:'  START_UPDATE_DETAILES_SPESIFIC_USER',
    SUCCESS_UPDATE_DETAILES_SPESIFIC_USER:'SUCCESS_UPDATE_DETAILES_SPESIFIC_USER',
    FAIL_UPDATE_DETAILES_SPESIFIC_USER:'  FAIL_UPDATE_DETAILES_SPESIFIC_USER',

    START_DELETE_SPESIFIC_PRODUCT:'  START_DELETE_SPESIFIC_PRODUCT',
    SUCCESS_DELETE_SPESIFIC_PRODUCT:'SUCCESS_DELETE_SPESIFIC_PRODUCT',
    FAIL_DELETE_SPESIFIC_PRODUCT:'  FAIL_DELETE_SPESIFIC_PRODUCT',

    START_DELETE_SPESIFIC_USER:'  START_DELETE_SPESIFIC_USER',
    SUCCESS_DELETE_SPESIFIC_USER:'SUCCESS_DELETE_SPESIFIC_USER',
    FAIL_DELETE_SPESIFIC_USER:'  FAIL_DELETE_SPESIFIC_USER',

    START_ADD_NEW_PRODUCT:'  START_ADD_NEW_PRODUCT',
    SUCCESS_ADD_NEW_PRODUCT:'SUCCESS_ADD_NEW_PRODUCT',
    FAIL_ADD_NEW_PRODUCT:'  FAIL_ADD_NEW_PRODUCT',
    
    START_GET_SPESIFIC_USER:'  START_GET_SPESIFIC_USER',
    SUCCESS_GET_SPESIFIC_USER:'SUCCESS_GET_SPESIFIC_USER',
    FAIL_GET_SPESIFIC_USER:'  FAIL_GET_SPESIFIC_USER'
};

