export const AuthActionsName={
    START_SIGNUP: 'START_SIGNUP',
    SUCCESS_SIGNUP: 'SUCCESS_SIGNUP',
    FAIL_SIGNUP:'FAIL_SIGNUP',
    START_SIGNIN:'START_SIGNIN',
    SUCCESS_SIGNIN:'SUCCESS_SIGNIN',
    FAIL_SIGNIN:'FAIL_SIGNIN',
     SIGNOUT:'SIGNOUT'

};