export const orderActionsName={
    START_ADD_ORDER:' START_ADD_ORDER',
    SUCCESS_ADD_ORDER:'SUCCESS_ADD_ORDER',
    FAIL_ADD_ORDER:'FAIL_ADD_ORDER',
    START_GET_USER_ORDERS:'START_GET_USER_ORDERS',
    SUCCESS_USER_ORDERS:' SUCCESS_USER_ORDERS',
FAIL_USER_ORDERS:'FAIL_USER_ORDERS',
START_GET_SPESIFIC_ORDER:'START_GET_SPESIFIC_ORDER',
SUCCESS_GET_SPESIFIC_ORDER:'SUCCESS_GET_SPESIFIC_ORDER',
FAIL_GET_SPESIFIC_ORDER:'FAIL_GET_SPESIFIC_ORDER',}