export const userActionsName={
    START_GET_USER_PROFILE:'  START_GET_USER_PROFILE',
    SUCCESS_GET_USER_PROFILE:'SUCCESS_GET_USER_PROFILE',
    FAIL_GET_USER_PROFILE:'  FAIL_GET_USER_PROFILE',

    START_UPDATE_USER_PROFILE:'  START_UPDATE_USER_PROFILE',
    SUCCESS_UPDATE_USER_PROFILE:'SUCCESS_UPDATE_USER_PROFILE',
    FAIL_UPDATE_USER_PROFILE:'  FAIL_UPDATE_USER_PROFILE',
    
    START_UPDATE_USER_CART:'  START_UPDATE_USER_CART',
    SUCCESS_UPDATE_USER_CART:'SUCCESS_UPDATE_USER_CART',
    FAIL_UPDATE_USER_CART:'  FAIL_UPDATE_USER_CART',

    START_DELETE_USER_CART:'  START_DELETE_USER_CART',
    SUCCESS_DELETE_USER_CART:'SUCCESS_DELETE_USER_CART',
    FAIL_DELETE_USER_CART:'  FAIL_DELETE_USER_CART',
}